cards_detection:
  enclosing: minrect
  min_perimeter: 1500
  max_perimeter: 2500

image_description:
  captioning:
    captioning_models: []
    use_azure_detector: false
  
clue_generation:
  openai_model: text-curie-001
  questions_to_blip2: 0
