cards_detection:
  enclosing: minrect
  min_perimeter: 1500
  max_perimeter: 2500

image_description:
  openai_model: text-davinci-003
  captioning:
    models:
    - blip2
    - git-large-coco
    - blip-large
    use_azure_detector: false
  num_blip2_questions: 1
  
generate_clue:
  openai_model: text-davinci-003
  num_blip2_questions: 1
